# Generated by Django 4.1.4 on 2023-03-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_measurement_image_alter_measurement_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
